;; Pip's matrix kernel: Y[r][o] = X[r] . W[o] + B[o] with 128-bit SIMD (f32x4), four rows at a time.
;; Addresses are byte offsets into the shared memory; inDim must be a multiple of 4; b = 0 means no bias.
;; Build: node tools/build_wasm.js  (writes the compiled bytes into src/wasm.js)
(module
  (memory (export "memory") 1)
  (func $hsum (param $v v128) (result f32)
    (f32.add
      (f32.add (f32x4.extract_lane 0 (local.get $v)) (f32x4.extract_lane 1 (local.get $v)))
      (f32.add (f32x4.extract_lane 2 (local.get $v)) (f32x4.extract_lane 3 (local.get $v)))))
  (func (export "linear") (param $x i32) (param $rows i32) (param $in i32) (param $w i32) (param $b i32) (param $out i32) (param $y i32)
    (local $r i32) (local $o i32) (local $i i32) (local $wp i32) (local $inB i32) (local $outB i32)
    (local $x0 i32) (local $x1 i32) (local $x2 i32) (local $x3 i32) (local $yp i32)
    (local $a0 v128) (local $a1 v128) (local $a2 v128) (local $a3 v128) (local $wv v128) (local $bias f32)
    (local.set $inB (i32.shl (local.get $in) (i32.const 2)))
    (local.set $outB (i32.shl (local.get $out) (i32.const 2)))
    (local.set $r (i32.const 0))
    (block $done4
      (loop $rows4
        (br_if $done4 (i32.gt_s (i32.add (local.get $r) (i32.const 4)) (local.get $rows)))
        (local.set $x0 (i32.add (local.get $x) (i32.mul (local.get $r) (local.get $inB))))
        (local.set $x1 (i32.add (local.get $x0) (local.get $inB)))
        (local.set $x2 (i32.add (local.get $x1) (local.get $inB)))
        (local.set $x3 (i32.add (local.get $x2) (local.get $inB)))
        (local.set $o (i32.const 0))
        (local.set $wp (local.get $w))
        (loop $outs
          (local.set $a0 (v128.const i32x4 0 0 0 0))
          (local.set $a1 (v128.const i32x4 0 0 0 0))
          (local.set $a2 (v128.const i32x4 0 0 0 0))
          (local.set $a3 (v128.const i32x4 0 0 0 0))
          (local.set $i (i32.const 0))
          (loop $ins
            (local.set $wv (v128.load (i32.add (local.get $wp) (local.get $i))))
            (local.set $a0 (f32x4.add (local.get $a0) (f32x4.mul (local.get $wv) (v128.load (i32.add (local.get $x0) (local.get $i))))))
            (local.set $a1 (f32x4.add (local.get $a1) (f32x4.mul (local.get $wv) (v128.load (i32.add (local.get $x1) (local.get $i))))))
            (local.set $a2 (f32x4.add (local.get $a2) (f32x4.mul (local.get $wv) (v128.load (i32.add (local.get $x2) (local.get $i))))))
            (local.set $a3 (f32x4.add (local.get $a3) (f32x4.mul (local.get $wv) (v128.load (i32.add (local.get $x3) (local.get $i))))))
            (local.set $i (i32.add (local.get $i) (i32.const 16)))
            (br_if $ins (i32.lt_u (local.get $i) (local.get $inB))))
          (local.set $bias (if (result f32) (local.get $b)
            (then (f32.load (i32.add (local.get $b) (i32.shl (local.get $o) (i32.const 2)))))
            (else (f32.const 0))))
          (local.set $yp (i32.add (local.get $y) (i32.shl (i32.add (i32.mul (local.get $r) (local.get $out)) (local.get $o)) (i32.const 2))))
          (f32.store (local.get $yp) (f32.add (call $hsum (local.get $a0)) (local.get $bias)))
          (f32.store (i32.add (local.get $yp) (local.get $outB)) (f32.add (call $hsum (local.get $a1)) (local.get $bias)))
          (f32.store (i32.add (local.get $yp) (i32.shl (local.get $outB) (i32.const 1))) (f32.add (call $hsum (local.get $a2)) (local.get $bias)))
          (f32.store (i32.add (local.get $yp) (i32.mul (local.get $outB) (i32.const 3))) (f32.add (call $hsum (local.get $a3)) (local.get $bias)))
          (local.set $wp (i32.add (local.get $wp) (local.get $inB)))
          (local.set $o (i32.add (local.get $o) (i32.const 1)))
          (br_if $outs (i32.lt_u (local.get $o) (local.get $out))))
        (local.set $r (i32.add (local.get $r) (i32.const 4)))
        (br $rows4)))
    (block $done1
      (loop $rows1
        (br_if $done1 (i32.ge_s (local.get $r) (local.get $rows)))
        (local.set $x0 (i32.add (local.get $x) (i32.mul (local.get $r) (local.get $inB))))
        (local.set $o (i32.const 0))
        (local.set $wp (local.get $w))
        (loop $outs1
          (local.set $a0 (v128.const i32x4 0 0 0 0))
          (local.set $a1 (v128.const i32x4 0 0 0 0))
          (local.set $i (i32.const 0))
          (loop $ins1
            (local.set $a0 (f32x4.add (local.get $a0) (f32x4.mul (v128.load (i32.add (local.get $wp) (local.get $i))) (v128.load (i32.add (local.get $x0) (local.get $i))))))
            (local.set $i (i32.add (local.get $i) (i32.const 16)))
            (br_if $ins1 (i32.lt_u (local.get $i) (local.get $inB))))
          (local.set $bias (if (result f32) (local.get $b)
            (then (f32.load (i32.add (local.get $b) (i32.shl (local.get $o) (i32.const 2)))))
            (else (f32.const 0))))
          (f32.store (i32.add (local.get $y) (i32.shl (i32.add (i32.mul (local.get $r) (local.get $out)) (local.get $o)) (i32.const 2)))
            (f32.add (call $hsum (local.get $a0)) (local.get $bias)))
          (local.set $wp (i32.add (local.get $wp) (local.get $inB)))
          (local.set $o (i32.add (local.get $o) (i32.const 1)))
          (br_if $outs1 (i32.lt_u (local.get $o) (local.get $out))))
        (local.set $r (i32.add (local.get $r) (i32.const 1)))
        (br $rows1))))
)
