"""Build ../data/dictionary.js from WordNet 3.0 (Princeton; see training/data/wordnet/LICENSE).
One line per word: word<TAB>pos<TAB>definition (most common sense only). Download with:
  curl -L -o data/wordnet.zip https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/wordnet.zip && (cd data && unzip wordnet.zip)
"""
import json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
WN = os.path.join(HERE, "data", "wordnet")
words_js = open(os.path.join(HERE, "..", "data", "words.js")).read()
common = set(json.loads(words_js.split("Pip.data.words = ")[1].rstrip(";\n")).split(" "))

def gloss(pos, offset):
    with open(os.path.join(WN, "data." + pos), "rb") as f:
        f.seek(offset)
        line = f.readline().decode("utf8")
    g = line.split(" | ", 1)[1].strip()
    d = re.split(r';\s*"', g)[0].strip().rstrip(";").strip()
    d = re.sub(r"\s*\([^)]*\)", "", d) if len(d) > 150 else d
    return d[:170].rsplit(" ", 1)[0] if len(d) > 170 else d

entries = {}
for pos, tag in (("noun", "n"), ("verb", "v"), ("adj", "a"), ("adv", "r")):
    for line in open(os.path.join(WN, "index." + pos)):
        if line.startswith(" "):
            continue
        p = line.split()
        lemma, synset_cnt, p_cnt = p[0], int(p[2]), int(p[3])
        tagsense = int(p[5 + p_cnt])
        offsets = [int(x) for x in p[6 + p_cnt:]]
        word = lemma.replace("_", " ")
        if len(word) < 2 or re.search(r"[^a-z' .-]", word):
            proper = True  # capitalized in data files; index is lowercase anyway
        n_words = word.count(" ") + 1
        keep = (tag == "n" and (n_words == 1 or tagsense > 0 or word in common)) or (tag != "n" and (tagsense > 0 or word in common))
        if not keep or n_words > 3:
            continue
        if word in entries and entries[word][2] >= tagsense:
            continue
        entries[word] = (tag, offsets[0], tagsense)

lines = []
for word, (tag, off, _) in sorted(entries.items()):
    try:
        d = gloss({"n": "noun", "v": "verb", "a": "adj", "r": "adv"}[tag], off)
    except Exception:
        continue
    if d:
        lines.append(f"{word}\t{tag}\t{d}")
blob = "\n".join(lines)
out = os.path.join(HERE, "..", "data", "dictionary.js")
with open(out, "w") as f:
    f.write("/* word definitions from WordNet 3.0 (c) Princeton University, used under the WordNet license (generated by training/export_dictionary.py) */\n")
    f.write("(typeof window !== 'undefined' ? window : global).Pip.data = (typeof window !== 'undefined' ? window : global).Pip.data || {};\n")
    f.write("(typeof window !== 'undefined' ? window : global).Pip.data.dictionary = " + json.dumps(blob) + ";\n")
print(len(lines), "entries,", os.path.getsize(out) // 1024, "KB")
for w in ("quokka", "dog", "einstein", "paris", "happy", "run", "photosynthesis", "love", "minecraft", "axolotl"):
    print(w, "->", entries.get(w) and [l for l in lines if l.startswith(w + "\t")][:1])
