"""Build ../data/dictionary.js from WordNet 3.0 (Princeton; see training/data/wordnet/LICENSE).
One line per word: word<TAB>pos<TAB>definition (most common sense only). Download with:
  curl -L -o data/wordnet.zip https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/wordnet.zip && (cd data && unzip wordnet.zip)
"""
import json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
WN = os.path.join(HERE, "data", "wordnet")
words_js = open(os.path.join(HERE, "..", "data", "words.js")).read()
common = set(json.loads(words_js.split("Pip.data.words = ")[1].rstrip(";\n")).split(" "))

def gloss(pos, offset):
    with open(os.path.join(WN, "data." + pos), "rb") as f:
        f.seek(offset)
        line = f.readline().decode("utf8")
    g = line.split(" | ", 1)[1].strip()
    d = re.split(r';\s*"', g)[0].strip().rstrip(";").strip()
    d = re.sub(r"\s*\([^)]*\)", "", d) if len(d) > 150 else d
    return d[:170].rsplit(" ", 1)[0] if len(d) > 170 else d

entries = {}
for pos, tag in (("noun", "n"), ("verb", "v"), ("adj", "a"), ("adv", "r")):
    for line in open(os.path.join(WN, "index." + pos)):
        if line.startswith(" "):
            continue
        p = line.split()
        lemma, synset_cnt, p_cnt = p[0], int(p[2]), int(p[3])
        tagsense = int(p[5 + p_cnt])
        offsets = [int(x) for x in p[6 + p_cnt:]]
        word = lemma.replace("_", " ")
        if len(word) < 2 or re.search(r"[^a-z' .-]", word):
            proper = True  # capitalized in data files; index is lowercase anyway
        n_words = word.count(" ") + 1
        # every single word (so "loquacious" and "defenestrate" are there), plus common or frequent phrases
        keep = n_words == 1 or tagsense > 0 or word in common
        if not keep or n_words > 3:
            continue
        if word in entries and entries[word][2] >= tagsense:
            continue
        entries[word] = (tag, offsets[0], tagsense)

lines = []
for word, (tag, off, _) in sorted(entries.items()):
    try:
        d = gloss({"n": "noun", "v": "verb", "a": "adj", "r": "adv"}[tag], off)
    except Exception:
        continue
    if d:
        lines.append(f"{word}\t{tag}\t{d}")
blob = "\n".join(lines)

# a small thesaurus: for each common word, the other words in its synsets (and "similar to" adjectives)
def synset_words(pos, offset):
    with open(os.path.join(WN, "data." + pos), "rb") as f:
        f.seek(offset)
        p = f.readline().decode("utf8").split(" | ")[0].split()
    w_cnt = int(p[3], 16)
    ws = [p[4 + 2 * i].lower() for i in range(w_cnt)]
    k = 4 + 2 * w_cnt
    p_cnt = int(p[k]); ptrs = []
    for i in range(p_cnt):
        sym, off, ppos = p[k + 1 + 4 * i], int(p[k + 2 + 4 * i]), p[k + 3 + 4 * i]
        ptrs.append((sym, off, ppos))
    return [re.sub(r"\(.*\)$", "", w) for w in ws], ptrs
PFILE = {"n": "noun", "v": "verb", "a": "adj", "s": "adj", "r": "adv"}
thes = {}
for pos in ("noun", "verb", "adj", "adv"):
    for line in open(os.path.join(WN, "index." + pos)):
        if line.startswith(" "):
            continue
        p = line.split()
        lemma, p_cnt = p[0], int(p[3])
        if "_" in lemma or lemma not in common:
            continue
        offsets = [int(x) for x in p[6 + p_cnt:]][:4]
        out = thes.setdefault(lemma, [])
        for off in offsets:
            try:
                ws, ptrs = synset_words(pos, off)
            except Exception:
                continue
            for w in ws:
                if w != lemma and "_" not in w and w not in out:
                    out.append(w)
            if pos == "adj":
                for sym, o2, pp in ptrs:
                    if sym == "&":
                        try:
                            ws2, _ = synset_words("adj", o2)
                        except Exception:
                            continue
                        for w in ws2:
                            if w != lemma and "_" not in w and w not in out:
                                out.append(w)
        thes[lemma] = out[:24]
thes = {k: v for k, v in thes.items() if v}
tblob = "\n".join(k + "\t" + " ".join(v) for k, v in sorted(thes.items()))
print(len(thes), "thesaurus entries,", len(tblob) // 1024, "KB")
out = os.path.join(HERE, "..", "data", "dictionary.js")
with open(out, "w") as f:
    f.write("/* word definitions from WordNet 3.0 (c) Princeton University, used under the WordNet license (generated by training/export_dictionary.py) */\n")
    f.write("(typeof window !== 'undefined' ? window : global).Pip.data = (typeof window !== 'undefined' ? window : global).Pip.data || {};\n")
    f.write("(typeof window !== 'undefined' ? window : global).Pip.data.dictionary = " + json.dumps(blob) + ";\n")
    f.write("(typeof window !== 'undefined' ? window : global).Pip.data.thesaurus = " + json.dumps(tblob) + ";\n")
print(len(lines), "entries,", os.path.getsize(out) // 1024, "KB")
for w in ("quokka", "dog", "einstein", "paris", "happy", "run", "photosynthesis", "love", "minecraft", "axolotl"):
    print(w, "->", entries.get(w) and [l for l in lines if l.startswith(w + "\t")][:1])
