"""Export trained models to ../data/*.js for the browser / Node runtime (src/neural.js).

  python3 export.py tokenizer        -> data/tokenizer.js
  python3 export.py encoder          -> data/encoder.js + data/bank.js (encodes the reply bank)
  python3 export.py gpt [ckpt.pt]    -> data/gpt.js

Weights are stored as int8 with one float32 scale per row (matrices) or float32 (vectors),
packed into one base64 blob inside a .js file, so the page also works when opened from file://.
"""
import base64, json, os, struct, sys
import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
OUT = os.path.join(HERE, "..", "data")
HEADER = "(typeof window !== 'undefined' ? window : global).Pip.data = (typeof window !== 'undefined' ? window : global).Pip.data || {};\n"


def write_js(name, key, obj, note):
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        f.write(f"/* {note} (generated by training/export.py) */\n" + HEADER)
        f.write(f"(typeof window !== 'undefined' ? window : global).Pip.data.{key} = ")
        json.dump(obj, f, separators=(",", ":"))
        f.write(";\n")
    print(f"wrote {path} ({os.path.getsize(path) / 1e6:.1f} MB)")


def pack(state, q8=lambda name, t: t.dim() == 2):
    blob = bytearray()
    tensors = {}
    for name, t in state.items():
        t = t.detach().float().cpu()
        if q8(name, t):
            w = t.numpy()
            scale = np.abs(w).max(axis=1) / 127.0
            scale[scale == 0] = 1e-8
            q = np.clip(np.round(w / scale[:, None]), -127, 127).astype(np.int8)
            tensors[name] = [list(w.shape), len(blob), "q8"]
            blob += scale.astype("<f4").tobytes() + q.tobytes()
        else:
            tensors[name] = [list(t.shape), len(blob), "f32"]
            blob += t.numpy().astype("<f4").tobytes()
    return tensors, base64.b64encode(bytes(blob)).decode()


def dequant(state):
    """What the JS side will see after int8 round-trip (for checking quality)."""
    out = {}
    for k, t in state.items():
        t = t.detach().float()
        if t.dim() == 2:
            s = t.abs().max(dim=1).values / 127.0
            s[s == 0] = 1e-8
            out[k] = torch.clamp(torch.round(t / s[:, None]), -127, 127) * s[:, None]
        else:
            out[k] = t
    return out


def export_tokenizer():
    spec = json.load(open(os.path.join(DATA, "bpe.json")))
    vocab = spec["model"]["vocab"]
    inv = [None] * len(vocab)
    for tok, i in vocab.items():
        inv[i] = tok
    merges = [m if isinstance(m, str) else " ".join(m) for m in spec["model"]["merges"]]
    specials = [a["content"] for a in spec["added_tokens"]]
    write_js("tokenizer.js", "tokenizer", {"vocab": inv, "merges": merges, "specials": specials}, "PipGPT byte-level BPE tokenizer")


import re
# lines that don't belong in a companion's mouth, whatever the context
BANK_DROP = re.compile(
    r"\b(nice (chatting|talking|speaking|meeting|to meet|to chat|to talk)|talk(ing)? to you (later|soon|tomorrow)|chat (later|soon)|"
    r"have a (good|great|nice|wonderful|lovely) (day|night|evening|weekend|one|time)|good ?night|good ?bye|bye|see you|see ya|take care|"
    r"gotta go|got to go|have to go|signing off|drunk|beer|wine|vodka|whiskey|alcohol|booze|weed|marijuana|drugs?|cocaine|smok\w*|"
    r"cigarettes?|vap\w+|guns?|shoot\w*|kill\w*|murder\w*|blood\w*|sexy|kiss\w*|steal|stole|rob\w*|hide the|jail|prison|"
    r"hell|damn|crap|sucks?|stupid|idiot|dumb|shut up|hate you|you said that already|you already said|i don'?t care|whatever|"
    r"who cares|leave me alone|go away|none of your business|i don'?t know you|married|divorce\w*|pregnan\w*|church|god|jesus|"
    r"pray\w*|bible|politic\w*|trump|obama|democrat\w*|republican\w*|vote|war|army|military)\b", re.I)


def export_encoder():
    sys.path.insert(0, HERE)
    from train_encoder import Encoder, encode_batch, MAXLEN
    from tokenizers import Tokenizer
    model = Encoder()
    model.load_state_dict(torch.load(os.path.join(HERE, "runs", "enc", "final.pt")))
    model.eval()
    state = {k: v for k, v in model.state_dict().items() if k != "logit_scale"}
    tensors, blob = pack(state)
    cfg = {"d": 256, "layers": 2, "heads": 4, "out": 128, "maxlen": MAXLEN}
    write_js("encoder.js", "encoder", {"config": cfg, "tensors": tensors, "blob": blob, "params": sum(v.numel() for v in state.values())},
             "Pip reply-scoring dual encoder")
    # encode the bank with the (int8 round-tripped) model so JS and Python agree
    model.load_state_dict({**dequant(state), "logit_scale": model.logit_scale})
    tok = Tokenizer.from_file(os.path.join(DATA, "bpe.json"))
    bank = json.load(open(os.path.join(DATA, "bank.json")))
    srcs = json.load(open(os.path.join(DATA, "bank_src.json"))) if os.path.exists(os.path.join(DATA, "bank_src.json")) else [None] * len(bank)
    keep = [i for i, t in enumerate(bank) if not BANK_DROP.search(t)]
    print(f"bank: kept {len(keep)} of {len(bank)} lines after the content filter")
    bank = [bank[i] for i in keep]
    srcs = [srcs[i] for i in keep] if srcs[0] is not None else None
    embs = []
    with torch.no_grad():
        for i in range(0, len(bank), 512):
            ids, lens = encode_batch(tok, [" " + t.lower() for t in bank[i:i + 512]], False)
            embs.append(model.resp(torch.from_numpy(ids), torch.from_numpy(lens)).numpy())
    E = np.concatenate(embs)
    scale = np.abs(E).max(axis=1) / 127.0
    q = np.clip(np.round(E / scale[:, None]), -127, 127).astype(np.int8)
    blob = base64.b64encode(scale.astype("<f4").tobytes() + q.tobytes()).decode()
    obj = {"texts": bank, "dim": int(E.shape[1]), "emb": blob}
    if srcs:
        obj["src"] = srcs
    write_js("bank.js", "bank", obj, f"{len(bank)} human-written replies with their encoder embeddings")
    # the message each reply originally answered (for keyword matching in the browser)
    want = {t: i for i, t in enumerate(bank)}
    ctx = [""] * len(bank)
    for line in open(os.path.join(DATA, "dialogs.jsonl")):
        d = json.loads(line)
        turns = d["turns"]
        for j in range(1, len(turns)):
            i = want.get(turns[j].strip())
            if i is not None and not ctx[i]:
                ctx[i] = re.sub(r"<\|(me|you)\|>", "", turns[j - 1]).lower()[:160]
    print("contexts found for", sum(1 for c in ctx if c), "replies")
    write_js("bankctx.js", "bankctx", ctx, "the message each bank reply originally answered")


def export_gpt(path):
    sys.path.insert(0, HERE)
    from train_gpt import GPT, Config
    ck = torch.load(path)
    state = ck["model"] if "model" in ck else ck
    c = Config()
    tensors, blob = pack(state)
    params = sum(v.numel() for v in state.values())
    cfg = {"vocab": c.vocab, "ctx": c.ctx, "d": c.d, "layers": c.layers, "heads": c.heads}
    write_js("gpt.js", "gpt", {"config": cfg, "tensors": tensors, "blob": blob, "params": params, "step": ck.get("step") if isinstance(ck, dict) else None},
             f"PipGPT, a {params/1e6:.1f}M-parameter transformer trained from scratch")


if __name__ == "__main__":
    what = sys.argv[1]
    if what == "tokenizer":
        export_tokenizer()
    elif what == "encoder":
        export_encoder()
    elif what == "gpt":
        export_gpt(sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "runs", "gpt", "final.pt"))
