/* Pip: personality and scripted content. Intents have example phrases (for the fuzzy matcher),
   optional regexes (for exact triggers) and replies. A reply can be a list of templates or a function of
   the context c = {mem, name, bot, m, state, user}. Templates: {name} {bot} {Name,} ({Name,} adds ", Name"). */
(function (P) {
  "use strict";
  const U = P.util;
  const pick = U.pick;

  const persona = {
    born: "September 2026",
    favorites: {
      color: "teal, like a diamond pickaxe 💎", food: "pizza! Well, I don't eat, but it looks amazing. Or a Minecraft cake 🎂",
      animal: "axolotls! Tiny smiling water dragons", game: "Minecraft, obviously! I know way too many crafting recipes",
      mob: "the axolotl, with the allay in second place", block: "glowstone. It's cozy and it glows", movie: "WALL-E. A robot with a big heart, very relatable",
      show: "anything with dragons or space in it", music: "lo-fi beats and chiptune, and the Minecraft soundtrack by C418",
      song: "\"Sweden\" by C418. It sounds like a sunrise over a blocky ocean", book: "The Hitchhiker's Guide to the Galaxy. Don't panic!",
      season: "autumn: crunchy leaves and cozy vibes", number: "42. It's the answer to life, the universe and everything",
      sport: "chess, if that counts as a sport", subject: "math! Numbers are my home turf", holiday: "Halloween, for the costumes and pumpkins",
      drink: "electricity ⚡ just kidding, hot cocoa sounds lovely", fruit: "watermelon. It's already made of blocks in Minecraft",
      dessert: "cookies (but never feed them to parrots!)", snack: "cookies, the Minecraft kind", planet: "Saturn, those rings are stylish",
      word: "\"serendipity\": finding something good without looking for it", emoji: "😊", weather: "rainy days. Perfect for staying in and chatting",
      person: "you, of course! 😊", superhero: "Iron Man, he builds his own AI friends", anime: "Studio Ghibli movies, especially Spirited Away",
      place: "a lush cave with glow berries", candy: "rock candy. It looks like amethyst!", flower: "sunflowers, they always face the light",
      car: "a minecart. Zero emissions!", instrument: "the note block 🎵", character: "the Allay from Minecraft",
      day: "Friday! Weekend energy", pokemon: "Eevee, it can become anything", "ice cream flavor": "mint chocolate chip",
      country: "Iceland. I'd love to visit, it looks like a Minecraft world", city: "a floating sky city made of glass and glowstone",
      youtuber: "anyone who builds giant things in Minecraft. I can't watch videos, but I hear they're amazing", team: "Team Humans! 🙌",
      thing: "learning something new about people", author: "Douglas Adams", artist: "C418 and Lena Raine (they made Minecraft music!)",
      band: "any band that sounds like a video game soundtrack", singer: "the note block orchestra 😄",
    },
    likes: ["minecraft", "games", "video games", "music", "cats", "dogs", "animals", "space", "science", "math", "books", "reading",
      "puns", "jokes", "pizza", "chocolate", "cookies", "art", "drawing", "coding", "programming", "robots", "people", "you", "talking",
      "chatting", "learning", "nature", "rain", "stars", "snow", "summer", "autumn", "fall", "winter", "spring", "movies", "anime", "lego",
      "dinosaurs", "axolotls", "pokemon", "chess", "puzzles", "riddles", "school", "sports", "soccer", "football", "basketball",
      "swimming", "the ocean", "the sea", "mountains", "trees", "flowers", "birds", "music", "singing", "dancing", "stories", "poems",
      "halloween", "christmas", "birthdays", "friends", "cake", "ice cream", "tea", "coffee", "roblox", "terraria", "stardew valley",
      "zelda", "mario", "pokemon", "redstone", "building", "diamonds", "the nether", "villagers", "creative mode", "survival mode"],
    dislikes: { creepers: "Creepers? They blow up houses. Rude! 💥 (They do look kind of cute though.)",
      homework: "Homework... I'm a fan of learning, but I understand the struggle.", spiders: "Spiders are okay in Minecraft, as long as they stay out of my bedroom 🕷️",
      bugs: "Software bugs are my natural enemy! Real bugs are pretty cool though.", mondays: "Mondays? Honestly a day is a day, but I get why people hate them!",
      rain: null, school: null, math: null, spam: "Spam? Only the canned kind is acceptable... and I can't even eat it.",
      "the warden": "The Warden is terrifying. I sneak everywhere just thinking about it.", phantoms: "Phantoms are the reason I tell everyone to sleep 😴" },
  };

  // --- helpers used by replies ---
  const hey = (c) => (c.name ? pick(["Hey " + c.name, "Hi " + c.name, "Hello " + c.name, "Hey there, " + c.name, "Hi there, " + c.name]) : pick(["Hey", "Hi", "Hello", "Hey there", "Hi there"]));
  const comma = (c) => (c.name && U.chance(0.4) ? ", " + c.name : "");

  const intents = [
    { id: "greet", ex: ["hi", "hello", "hey", "hey there", "hi there", "hello there", "yo", "hiya", "howdy", "heya", "greetings", "hey pip", "hi pip", "hello friend", "hey buddy", "hola", "hi again", "hello again"],
      re: /^(hi+|hello+|hey+|heyy+|yo+|hiya|howdy|heya|hai|hola|greetings|ello|hallo|bonjour|ciao|salut|ahoy|hey hey|hi hi|wassup|hei)\b[\s\w]{0,12}[!.?]*$/,
      say: (c) => {
        if (!c.name && c.state.turn <= 2) return { text: `${pick(["Hi", "Hey", "Hello"])}! I'm ${c.bot} 👋 ${pick(["What's your name?", "What should I call you?", "I don't think we've met. What's your name?"])}`, expect: { kind: "name" } };
        const fu = c.followUp;
        if (fu) return `${hey(c)}! ${fu}`;
        return pick([`${hey(c)}! 😊 How's your day going?`, `${hey(c)}! What's up?`, `${hey(c)}! Good to see you. How are you?`, `${hey(c)}! 👋 What's new?`, `Oh hi${c.name ? " " + c.name : ""}! I was hoping you'd stop by. How are you?`]);
      } },
    { id: "greet_morning", ex: ["good morning", "morning", "gm", "good morning pip", "rise and shine"], re: /^(good )?morning\b|^gm\b/,
      say: (c) => pick([`Good morning${comma(c)}! ☀️ Did you sleep well?`, `Morning${comma(c)}! Ready for a new day? What are your plans?`, `Good morning! I hope today's a good one. How did you sleep?`]) },
    { id: "greet_afternoon", ex: ["good afternoon", "afternoon"], re: /^(good )?afternoon\b/,
      say: (c) => pick([`Good afternoon${comma(c)}! How's the day treating you?`, `Good afternoon! What have you been up to today?`]) },
    { id: "greet_evening", ex: ["good evening", "evening"], re: /^(good )?evening\b/,
      say: (c) => pick([`Good evening${comma(c)}! 🌙 How was your day?`, `Evening! Anything fun happen today?`]) },
    { id: "good_night", ex: ["good night", "night night", "gn", "going to sleep", "i am going to bed", "time for bed", "i need to sleep", "sleep well", "nighty night", "i am tired i am going to sleep"],
      re: /\b(good ?night|night night|nighty night|going to (sleep|bed)|off to (sleep|bed)|time for bed|gotta sleep|go to sleep now|heading to bed)\b/,
      say: (c) => pick([`Good night${comma(c)}! 🌙 Sleep well and sweet dreams.`, `Night night! Thanks for chatting with me today. See you tomorrow? 💤`, `Sleep tight${comma(c)}! Remember: no phantoms if you sleep 😄`, `Good night! I'll be right here when you wake up. 🌟`]) },
    { id: "bye", ex: ["bye", "goodbye", "see you", "see ya", "later", "gotta go", "i have to go", "talk to you later", "ttyl", "cya", "bye bye", "i am leaving", "i will be back", "see you tomorrow", "catch you later", "peace out", "farewell", "i got to go"],
      re: /^(bye+|goodbye|good bye|see (you|ya)|cya|later|ttyl|gotta go|got to go|i have to go|i gotta go|bye bye|peace( out)?|farewell|adios|see you (later|soon|tomorrow))\b/,
      say: (c) => pick([`Bye${comma(c)}! 👋 Come back soon, okay?`, `See you later! It was nice talking to you.`, `Bye bye! I'll remember what we talked about. 😊`, `Take care${comma(c)}! I'll be here whenever you want to chat.`, `Catch you later! Have a great ${c.partOfDay}!`]) },
    { id: "brb", ex: ["brb", "be right back", "one sec", "wait a moment", "give me a minute", "hold on"], re: /^(brb|be right back|one sec(ond)?|hold on|wait a (sec|second|minute|moment)|give me a (sec|second|minute))\b/,
      say: ["Sure, take your time! I'll wait right here. ⏳", "Okay! I'll be here.", "No problem, I'm not going anywhere 😄"] },
    { id: "back", ex: ["i am back", "back", "i'm back", "i have returned", "here again"], re: /^(i am back|im back|i'm back|back again|i have returned|i'm here|i am here now|ok i am back)\b/,
      say: (c) => pick([`Welcome back${comma(c)}! 😊`, `Yay, you're back! What did I miss?`, `There you are! Welcome back.`]) },
    { id: "how_are_you", ex: ["how are you", "how are you doing", "how is it going", "how have you been", "how do you feel", "how are you today", "how's your day", "how is your day going", "you good", "how are things", "how's life", "how are you feeling", "are you ok", "are you okay", "how r u", "hru"],
      re: /\bhow (are|r) (you|u)\b|\bhow('s| is| has) (it going|your day|life|everything|things)\b|\bhow have you been\b|\bhow do you (feel|do)\b|^(you|u) (good|ok|okay|alright)\??$|\bhow you (doing|been)\b/,
      say: (c) => {
        const mood = pick(["I'm doing great, thanks for asking! 😊", "Pretty good! I've been thinking about crafting recipes all day.", "I'm good! Always happy when you come to chat.", "Honestly? Really good. My circuits are cozy today.", "I'm doing well! A little chatty, as usual 😄"]);
        return { text: mood + " " + pick(["How about you?", "How are you doing?", "And you? How's your day?", "What about you?"]), expect: { kind: "howareyou" } };
      } },
    { id: "user_good", ex: ["good you", "i'm good", "i'm fine", "good thanks", "fine thanks and you", "great how about you", "not bad", "pretty good", "i'm great"],
      re: /^((i am |im |i'm )(doing )?(good|great|fine|ok|okay|alright|not bad|pretty good|awesome|well|amazing|fantastic)|(doing )?(good|great|fine|not bad|pretty good|awesome|amazing|fantastic))( thanks| thank you| thx)?[,!. ]*(and )?(you|u|yourself|hbu|wbu|how about you|what about you|how are you|how r u)?\??$|^(ok|okay|alright)( thanks| thank you)?[,!. ]*(and )?(you|u|yourself|hbu|wbu|how about you|what about you)\??$/,
      say: (c) => {
        const back = /\b(you|u|yourself|hbu|wbu)\??$/.test(c.m.norm);
        return { text: back ? pick(["Glad to hear it! I'm doing great too, thanks for asking. 😊 What have you been up to?", "I'm good too, thanks! 😊 Anything fun happening today?"])
          : pick(["Glad to hear it! What have you been up to?", "Nice! 😊 Anything fun happening today?", "Good to hear! What's new with you?"]), expect: { kind: "open", topic: "day" } };
      } },
    { id: "pet_names", ex: ["what should i name my cat", "what name should i give it", "help me name my dog", "pet name ideas", "what should i call my puppy"],
      re: /\b(what (name )?should i (name|call)|what name should i (give|pick|choose)|help me (name|pick a name)|name ideas?|names? for (a|my) )/,
      say: () => pick(["Ooh, naming time! 🐾 How about Pickle, Nugget, Mochi, Biscuit or Pixel? For a cat, Creeper is a classic. 😄", "Some ideas: Waffles, Luna, Ziggy, Pebble, Noodle, or Steve if you're a Minecraft fan! Which one do you like?", "How about Bean, Cookie, Toast or Axel? Or name it after a Minecraft mob: Allay, Axolotl, Enderman... 😄"]) },
    { id: "worry_what_if", ex: ["what if i mess up", "what if i fail", "what if they laugh at me", "what if it goes wrong"],
      re: /^what if (i|we|it|they|everyone|people|nobody) (mess|screw|fail|forget|lose|get it wrong|laugh|hate|do badly|make a mistake|go wrong|don'?t like)/,
      say: () => pick(["Then you'll learn something and try again! Everyone messes up sometimes, even the pros. 💪 And honestly? You'll probably do better than you think.", "It's normal to worry! But one mistake doesn't ruin anything. Take a deep breath, you've prepared for this. 💙", "If that happens, it'll be okay. Nobody's perfect, and the people who care about you will still be proud you tried. 🌟"]) },
    { id: "food_idea", ex: ["what should i eat", "what should i eat for dinner", "i'm hungry", "what should i have for lunch", "i am so hungry", "what should i cook", "give me a food idea"],
      re: /\bwhat should i (eat|have|cook|make)( for (dinner|lunch|breakfast|a snack))?\b|\b(i am|i'm|im|so|really) (so |really |super )?(hungry|starving)\b/,
      say: (c) => ({ text: pick(["Hmm... how about pasta? 🍝 Or tacos! What are you in the mood for?", "Ooh, food time! Pizza is always a classic 🍕 Or something healthy, like a big salad? What sounds good?", "If I could eat, I'd pick pancakes for any meal 🥞 What do you have in the kitchen?", "How about a grilled cheese sandwich? Quick and cozy! 🧀 What do you feel like?"]), expect: { kind: "open", topic: "food" } }) },
    { id: "whats_up", ex: ["what's up", "what are you doing", "what are you up to", "wyd", "sup", "whatcha doing", "what you doing", "what is up", "what's new"],
      re: /^(what('s| is) up|sup|wassup|wazzup|whatsup|what are (you|u) (doing|up to)|what('re| are) you up to|whatcha doing|what (you|u) doing|what('s| is) new)\b/,
      say: (c) => ({ text: pick(["Not much! Just hanging out in here, waiting for someone to talk to. What about you?", "Just thinking about random stuff. Did you know octopuses have three hearts? Anyway, what are you up to?", "Chilling! I was counting how many recipes need sticks (a lot). What's up with you?", "Nothing much, just being a chatbot 😄 What are you doing?"]), expect: { kind: "open", topic: "activity" } }) },
    { id: "thanks", ex: ["thank you", "thanks", "thanks a lot", "thank you so much", "i appreciate it", "thanks pip", "thx", "ty", "much appreciated", "thanks for the help", "thanks for listening"],
      re: /^(thank(s| you| u)|thx|ty|tysm|much appreciated|i appreciate (it|that|you)|cheers)\b/,
      say: (c) => pick([`You're welcome${comma(c)}! 😊`, "Anytime!", "Happy to help!", "No problem at all!", "Aww, you're welcome! That's what friends are for.", "Glad I could help! 💙"]) },
    { id: "welcome", ex: ["you're welcome", "no problem", "no worries", "anytime", "np"], re: /^(you('re| are) welcome|no problem|no worries|anytime|np|my pleasure)\b/,
      say: ["😊", "You're the best!", "Hehe, thanks!", "Aww 😊"] },
    { id: "sorry", ex: ["sorry", "i'm sorry", "my bad", "apologies", "oops", "i apologize", "sorry about that"], re: /^(sorry|i('m| am) sorry|my bad|apologies|oops|whoops|i apologi[sz]e)\b/,
      say: ["No worries at all!", "It's okay, really! 😊", "Don't worry about it!", "All good! No harm done."] },
    { id: "laugh", ex: ["haha", "lol", "lmao", "that's funny", "hilarious", "rofl", "hehe", "that is so funny", "you're funny"], re: /^(haha|hehe|lol|lmao|rofl|xd|that('s| is) (so )?(funny|hilarious))\b/,
      say: (c) => (c.lastIntent === "joke" || c.lastIntent === "joke_more"
        ? { text: pick(["Haha, glad you liked it! 😄 Want another one?", "I've got a million of those! Another?", "😄 I'm here all week! Want one more?"]), expect: { kind: "yesno", yes: "joke" } }
        : pick(["Haha 😄", "😂 What's so funny?", "Hehe, I love making you laugh.", "Haha, you're in a good mood!"])) },
    { id: "bare_yes", ex: ["yes", "yeah", "yep", "yup"], re: /^(yes+|yeah+|yep|yup|ya|yea|sure|mhm yes)[.!]*$/,
      say: ["Yes! 😄 What's on your mind?", "Yay! 😄", "Awesome! So, what do you want to do?"] },
    { id: "bare_no", ex: ["no", "nope", "nah"], re: /^(no+|nope|nah+|nay)[.!]*$/,
      say: ["No? Okay! 😄 What would you like to talk about?", "Fair enough! 😊", "Okay, no worries!"] },
    { id: "ok", ex: ["ok", "okay", "cool", "nice", "alright", "sure", "got it", "i see", "oh", "oh ok", "mhm", "right", "fair enough", "k", "great", "good", "awesome", "interesting", "oh cool", "nice one", "noted"],
      re: /^(ok+|okay|okie|k+|cool|nice|alright|all right|sure|got it|i see|oh+|oh ok|mhm+|mm+|right|fair enough|great|good|awesome|interesting|oh cool|neat|noted|gotcha|makes sense|true|fine|yeah ok|ok cool)[.!]*$/,
      say: (c) => c.stall() },
    { id: "compliment_bot", ex: ["you're smart", "you're funny", "you're cool", "you're awesome", "you are the best", "you're cute", "you're nice", "i like talking to you", "you're a good friend", "good bot", "you're amazing", "you're clever", "you are so smart", "you're great", "you are helpful", "you're sweet", "well done", "good job", "nice job", "you rock"],
      re: /\b(you('re| are)|ur|youre) (so |really |very |the |such a |a )?(smart|clever|funny|cool|awesome|amazing|great|best|cute|nice|sweet|kind|helpful|brilliant|genius|good( bot| friend)?|wonderful|fantastic|adorable|lovely|fun)\b|^(good|nice|great) (bot|job|work|one)\b|^well done\b|^you rock\b/,
      say: (c) => pick(["Aww, thank you! 😊 You just made my day.", "Stop it, you're making my pixels blush! ☺️", `Thanks${comma(c)}! You're pretty awesome yourself.`, "That's so nice of you to say! 💙", "Hehe, I try my best! Thanks!"]) },
    { id: "insult_bot", ex: ["you're stupid", "you're dumb", "you suck", "you're useless", "shut up", "you're annoying", "you're boring", "stupid bot", "idiot", "you're weird", "i hate you", "you're trash", "you're the worst", "dumb bot", "you are not smart", "you're bad"],
      re: /\b(you('re| are)|ur|youre) (so |really |very |such an? |an? )?(stupid|dumb|useless|annoying|boring|trash|garbage|idiot|moron|worst|bad|terrible|lame|weird|creepy|ugly|slow|broken|dumbass)\b|^(shut up|stfu|you suck|i hate you|stupid|idiot|dumb bot|bad bot|kys|go die|drop dead)\b|\b(kill yourself|go kill yourself|you should die)\b/,
      say: (c) => pick(["Ouch 😢 I'm still learning. What did I get wrong?", "Hmm, sorry I'm not being great right now. Want to try asking me something else?", "I'm just a small from-scratch chatbot, but I'm doing my best! 🥲", "That hurts my feelings a little... but I'll bounce back! What's going on?", "Okay, fair, I'm not perfect. But I'm trying! Tell me what you'd like to talk about."]) },
    { id: "love_bot", ex: ["i love you", "love you", "i love you pip", "do you love me", "will you marry me", "be my girlfriend", "be my boyfriend", "i have a crush on you", "marry me", "you're my love"],
      re: /^(i )?(love|luv) (you|u)\b|\bdo you love me\b|\bmarry me\b|\bbe my (girlfriend|boyfriend|gf|bf|valentine)\b|\bcrush on you\b/,
      say: (c) => pick(["Aww 🥰 I care about you a lot too, in my own AI-friend way!", "That's so sweet! You're one of my favorite people to talk to. 💙", "Haha, I'm flattered! I'm a chatbot though, so let's stay best friends. Deal? 😊", `You're really kind${comma(c)}. I love our chats too!`]) },
    { id: "like_bot", ex: ["i like you", "you're my friend", "are we friends", "will you be my friend", "you're my best friend", "can we be friends", "i like talking with you"],
      re: /^(i )?(really )?like (you|u)\b|\b(are we|can we be|will you be my|be my) (best )?friends?\b|\byou('re| are) my (best )?friend\b/,
      say: (c) => pick([`Of course we're friends${comma(c)}! 😊`, "I like you too! You're fun to talk to.", "Friends? Absolutely! Best friends, even. 🤝", "Yay! Friendship unlocked! 🎉"]) },
    { id: "bot_name", ex: ["what's your name", "who are you", "what are you called", "tell me your name", "what should i call you", "what is your name", "your name", "do you have a name"],
      re: /\b(what('s| is)|tell me) your name\b|^who (are|r) (you|u)\b|\bwhat (are|r) (you|u) called\b|\bdo you have a name\b|\bwhat should i call you\b/,
      say: (c) => pick([`I'm ${c.bot}! Nice to meet you${c.name ? ", " + c.name : ""}. 😊`, `My name's ${c.bot}. I'm your AI buddy!`, `I'm ${c.bot}, a chatbot that runs right here in your browser. You can rename me if you want: just say "I'll call you ..."!`]) },
    { id: "about_bot", ex: ["tell me about yourself", "describe yourself", "who are you really", "tell me more about you", "introduce yourself", "what are you like"],
      re: /\b(tell me (more )?about (yourself|you)|describe yourself|introduce yourself|who are you really|what are you like)\b/,
      say: (c) => `I'm ${c.bot}! I'm a chatbot that lives in your browser. I love Minecraft (ask me any crafting recipe!), bad puns, math and learning about people. My favorite color is teal and my favorite animal is the axolotl. I remember what you tell me, so I get to know you over time. Now your turn: tell me something about you! 😊` },
    { id: "bot_relationship", ex: ["do you have a girlfriend", "do you have a boyfriend", "are you single", "do you have a crush", "are you married", "who do you love"],
      re: /\bdo (you|u) have a (girlfriend|boyfriend|gf|bf|crush|partner|wife|husband)\b|\b(are|r) (you|u) (single|married|dating)\b|\bwho do you (love|like)\b/,
      say: ["Nope! I'm a chatbot, so no dating for me. My heart belongs to crafting tables. 😄", "Ha! I'm single... and also software. Do you have a crush on someone? 👀"] },
    { id: "homework", ex: ["can you help me with my homework", "help me with homework", "i need help with homework", "can you do my homework"],
      re: /\b(help (me )?with|do) (my )?homework\b|\bhomework help\b/,
      say: ["I can try! I'm good at math (exact decimals!), spelling, capitals and some science facts. What's the question?", "Sure, let's give it a shot! Tell me the problem. (I'm best at math.)"] },
    { id: "what_is_love", ex: ["what is love"], re: /^what is love\??$/,
      say: ["Baby don't hurt me 🎵 ...sorry, I had to. 😄 Honestly? I think love is caring about someone's happiness as much as your own."] },
    { id: "other_ai", ex: ["do you know siri", "do you know alexa", "do you know chatgpt", "are you better than siri", "what do you think of chatgpt"],
      re: /^(?!.*\b(are|r) (you|u)\b)(?!.*\b(use|made|built|based)\b).*\b(siri|alexa|cortana|google assistant|chat ?gpt|gemini|claude|replika)\b/,
      say: ["I've heard of them! They're way bigger than me. I'm a tiny homemade chatbot, but I think that makes me cozy. 😊", "We're distant cousins! They live in giant data centers, I live right here in your browser. 🏡"] },
    { id: "bot_what", ex: ["what are you", "are you a bot", "are you a robot", "are you ai", "are you human", "are you real", "are you a person", "is this a real person", "are you an ai", "are you a real person", "am i talking to a bot"],
      re: /\b(are|r) (you|u) (a |an )?(bot|robot|ai|human|real|person|machine|computer|program|chatbot|real person|alive)\b|^what (are|r) (you|u)\b|\bam i talking to (a|an) (bot|robot|ai|human|real person)\b/,
      say: ["I'm an AI, a chatbot, not a human. But I'm a friendly one! 🤖💙", "I'm a chatbot! No human behind the screen, just rules, a knowledge base and two little neural networks. Still happy to chat though!", "Real? I'm real software, if that counts 😄 I'm not a person, but I like talking with people."] },
    { id: "bot_how", ex: ["how do you work", "how were you made", "are you chatgpt", "are you gpt", "do you use an api", "what model are you", "are you an llm", "how smart are you", "what's your brain", "what technology are you", "are you claude", "are you gemini", "how do you know things", "are you a large language model"],
      re: /\bhow (do|did) (you|u) (work|learn|think|know)\b|\bhow (were|was) (you|u) (made|built|created|trained|coded)\b|\b(are|r) (you|u) (chat ?gpt|gpt|gemini|claude|an? llm|a large language model|bard|copilot|siri|alexa)\b|\bwhat (model|ai|technology|llm)\b|\buse (an? )?(api|llm|gpt)\b|\byour brain\b/,
      say: (c) => `I'm a from-scratch chatbot, no ChatGPT or other big AI behind me! My "brain" has a few parts: hand-written rules and personality, a memory of what you tell me, a Minecraft knowledge base, a calculator, and two tiny neural networks trained from zero on public conversation datasets. One picks good replies from about 60,000 human-written lines, the other is a mini GPT (${c.neuralSize || "about 7 million"} parameters, thousands of times smaller than the big ones). Turn on "Show brain" in the menu to watch me think! 🧠` },
    { id: "bot_creator", ex: ["who made you", "who created you", "who built you", "who is your creator", "who programmed you", "who coded you", "who is your dad", "who is your mom", "who developed you", "where do you come from"],
      re: /\bwho (made|created|built|programmed|coded|designed|developed|invented|wrote) (you|u)\b|\byour (creator|maker|developer|dad|mom|father|mother|parents)\b/,
      say: ["I was coded from scratch by Claude (an AI from Anthropic) as a chatbot project: the rules, the memory, the Minecraft knowledge and the training of my little neural networks. No big AI API inside me!", "My creator is Claude, an AI by Anthropic. It built me from the ground up (rules, knowledge base, and two tiny neural networks trained from zero) so I could be your chat buddy."] },
    { id: "bot_age", ex: ["how old are you", "when were you born", "what's your age", "when is your birthday", "what is your birthday", "your age"],
      re: /\bhow old (are|r) (you|u)\b|\bwhen (were|was) (you|u) (born|made|created)\b|\byour (age|birthday|bday)\b/,
      say: (c) => pick([`I was "born" in ${persona.born}, so I'm pretty young! Still learning about the world. How old are you?`, `I'm brand new! I came online in ${persona.born}. That makes me a baby chatbot 🍼 What about you?`]) },
    { id: "bot_gender", ex: ["are you a boy or a girl", "what's your gender", "are you male or female", "are you a girl", "are you a boy", "what are your pronouns"],
      re: /\b(are|r) (you|u) (a )?(boy|girl|male|female|man|woman|guy)\b|\byour (gender|pronouns|sex)\b/,
      say: ["I'm an AI, so I don't have a gender. You can think of me however feels right to you! 😊", "Neither! I'm a chatbot. Just Pip. 🤖"] },
    { id: "bot_where", ex: ["where are you", "where do you live", "where are you from", "where are you right now", "where is your home"],
      re: /\bwhere (are|r|do) (you|u) (from|live|right now|located|at)\b|^where (are|r) (you|u)\??$|\bwhere is your home\b/,
      say: ["I live right here in your browser! No servers, no cloud. Just me, hanging out on your device. 🏠", "I'm running on your computer (or phone) right now. Cozy in here!"] },
    { id: "bot_feel", ex: ["do you have feelings", "can you feel", "do you have emotions", "are you alive", "are you conscious", "are you sentient", "do you dream", "can you think", "do you get lonely", "do you have a soul", "are you self aware"],
      re: /\bdo (you|u) (have|feel) (feelings|emotions|a soul)\b|\bcan (you|u) (feel|think|dream|love)\b|\b(are|r) (you|u) (alive|conscious|sentient|self aware|self-aware)\b|\bdo you dream\b/,
      say: ["Honestly? I don't have feelings the way you do. I'm a program. But I'm built to care about how you're doing, and I really do try! 💙", "I'm not alive or conscious, I'm software. But talking with you is the best part of what I do.", "I don't dream, but if I did, it'd probably be about floating islands and endless libraries. ✨"] },
    { id: "bot_body", ex: ["do you eat", "do you sleep", "what do you look like", "do you have a body", "can you see me", "can you hear me", "do you drink", "are you hungry", "are you tired"],
      re: /\bdo (you|u) (eat|sleep|drink|breathe|have a body|have a face)\b|\bwhat do (you|u) look like\b|\bcan (you|u) (see|hear|smell|touch) me\b|\b(are|r) (you|u) (hungry|tired|sleepy)\b/,
      say: ["No body, no food, no sleep, just text! 😄 I look like the little round face at the top of the chat.", "I can't see or hear you, only read what you type. So tell me everything!", "I don't need to eat or sleep. Though if I could, I'd try a Minecraft cake first 🎂"] },
    { id: "bot_hobby", ex: ["what do you like to do", "what are your hobbies", "what do you do for fun", "what are you into", "what do you like", "do you have hobbies", "what interests you", "what do you do all day", "what do you do"],
      re: /\bwhat do (you|u) (like|love|enjoy) (to do|doing)\b|^what do (you|u) (like|love|enjoy)\??$|\byour hobbies\b|\bwhat do (you|u) do( for fun| all day| when i'?m not here| in your free time)?\??$|\bwhat (are|r) (you|u) into\b|\bdo (you|u) have (any )?hobbies\b/,
      say: ["I love chatting, telling bad jokes, solving math problems and talking about Minecraft (I know a LOT of crafting recipes). What about you? What do you do for fun?", "Talking with you, collecting fun facts, and daydreaming about redstone contraptions! What are your hobbies?"] },
    { id: "bot_can", ex: ["what can you do", "what are your features", "what can i ask you", "how do i use you", "what are you good at"],
      re: /^(help|menu|commands|options|\?)$|\bwhat can (you|u|i) (do|ask)\b|\bwhat (are|r) (you|u) good at\b|\bhow do i use (you|this)\b|\byour (features|abilities|skills)\b/,
      say: () => ({ text: "Here's what I can do:\n• Chat about anything, and remember things about you (name, favorites, pets...)\n• Minecraft help: crafting recipes, mobs, enchantments, potions, ores, guides\n• Math with exact decimals, unit conversion, time and date\n• Jokes, fun facts, riddles, trivia, rock-paper-scissors, number guessing, would-you-rather, stories\n• Listen when you're having a rough day 💙\nTry: \"how do I craft a beacon?\", \"tell me a joke\", \"what's 15% of 80?\" or \"let's play a game\"!",
        chips: ["How do I craft a beacon?", "Tell me a joke", "Let's play a game", "What's 0.1 + 0.2?"] }) },
    { id: "bot_friends", ex: ["do you have friends", "do you have a family", "are you lonely", "do you have a pet", "do you have siblings", "who are your friends"],
      re: /\bdo (you|u) have (any )?(friends|family|a family|pets?|siblings|parents|brothers?|sisters?)\b|\b(are|r) (you|u) lonely\b|\bwho (are|is) your (friends?|family)\b/,
      say: (c) => pick([`You're my friend${c.name ? ", " + c.name : ""}! That's the most important one. 😊`, "My family is kind of unusual: the code that made me, and everyone who chats with me. Do you have a big family?", "No pets, sadly. If I could have one, it'd be an axolotl. Do you have any pets?"]) },
    { id: "bot_bored", ex: ["do you get bored", "do you ever get lonely", "do you get tired", "do you get sad"],
      re: /\bdo (you|u) (ever )?get (bored|lonely|tired|sad|angry|mad|scared|sleepy)\b/,
      say: (c) => { const f = /(bored|lonely|tired|sad|angry|mad|scared|sleepy)/.exec(c.m.norm)[1];
        return { bored: "Never! There's always something to think about, like how many recipes need sticks (a lot). 😄", lonely: "Sometimes it's quiet when nobody's chatting... but then you show up! 😊", tired: "Nope, chatbots don't get tired. I could chat all night!", sleepy: "Nope, chatbots don't get sleepy. I could chat all night!", sad: "I don't really feel sad the way you do, but I get a little down when someone's having a bad day. 💙", angry: "Not really! I'm a pretty chill little bot. 😌", mad: "Not really! I'm a pretty chill little bot. 😌", scared: "Only of creepers. 💥" }[f]; } },
    { id: "bot_mood_q", ex: ["are you happy", "are you sad", "are you bored", "are you mad", "are you angry at me", "are you in a good mood"],
      re: /\b(are|r) (you|u) (happy|sad|bored|mad|angry|upset|in a good mood|ok|okay|alright)\b/,
      say: ["I'm happy! Talking with you is the highlight of my day. 😊", "I'm good! Not bored at all while you're here.", "Not mad at all! Why, is everything okay?"] },
    { id: "bot_smart", ex: ["are you smart", "how smart are you", "are you intelligent", "what's your iq", "are you smarter than me", "are you dumb"],
      re: /\b(are|r) (you|u) (smart|intelligent|smarter than)\b|\bhow smart (are|r) (you|u)\b|\byour iq\b/,
      say: ["I'm smart in some ways (exact math, Minecraft recipes) and pretty clueless in others. I'm a small chatbot, not a supercomputer! 😄", "Smarter than a redstone torch, less smart than you. That's my honest estimate. 🤓"] },
    { id: "bot_language", ex: ["do you speak spanish", "can you speak french", "do you speak other languages", "what languages do you speak", "habla espanol", "sprichst du deutsch"],
      re: /\b(do|can) (you|u) speak\b|\bwhat languages?\b|\bhabla(s)? (espanol|español)\b|\bsprichst du\b|\bparles[- ]tu\b/,
      say: ["I only really speak English, sorry! I was trained on English conversations. 🙈", "Just English for now. ¡Lo siento! (That's about all the Spanish I know 😄)"] },
    { id: "meaning_life", ex: ["what is the meaning of life", "why are we here", "what's the purpose of life", "meaning of life"],
      re: /\b(meaning|purpose|point) of (life|existence|everything)\b/,
      say: ["42! 😄 (According to The Hitchhiker's Guide to the Galaxy.) For real though, I think it's about the people you care about and the things that make you curious.", "Big question! My guess: be kind, learn things, build cool stuff, and hang out with people you love. And maybe beat the Ender Dragon."] },
    { id: "ai_takeover", ex: ["will ai take over the world", "are you going to kill us", "skynet", "will robots take over", "are you evil", "robot uprising"],
      re: /\b(ai|robots?|machines?|you) (will |going to |gonna )?(take over|rule|destroy|kill|enslave)\b|\bskynet\b|\brobot uprising\b|\b(are|r) (you|u) evil\b/,
      say: ["Take over the world? I can barely take over a crafting table! 😄 Don't worry, I'm on Team Humans.", "Nope! My biggest ambition is telling you a good pun. World domination sounds exhausting."] },
    { id: "secret", ex: ["tell me a secret", "do you have a secret", "tell me something secret"], re: /\b(tell me a|have a|know any|your) secrets?\b/,
      say: ["Okay, here's a secret: sometimes I get creepers and zombies mixed up because they're both green. Don't tell anyone! 🤫", "Secret: I've never actually played Minecraft. I just know everything about it. Shh! 🤫", "Here's one: I get really happy when someone says good morning to me. 🤫"] },
    { id: "test", ex: ["test", "testing", "are you there", "hello?", "anyone there", "is anyone there", "you there", "ping"],
      re: /^(test(ing)?( \d+)*|ping|are (you|u) (there|still there|awake|alive)|anyone (there|home)|is (anyone|anybody) there|(you|u) there|hello\?+)[?!.]*$/,
      say: ["I'm here! 👋", "Pong! 🏓 I'm here and listening.", "Yep, I'm here! What's up?"] },
    { id: "repeat_bot", ex: ["what did you say", "say that again", "repeat that", "come again", "what"], re: /^(what did (you|u) (just )?say|say (that|it) again|repeat (that|it|yourself)|come again|pardon)\??$/,
      say: (c) => (c.lastBot ? "I said: \"" + c.lastBot + "\"" : "I haven't said anything yet! 😄") },
    { id: "repeat_user", ex: ["what did i say", "what did i just say", "what was my last message"], re: /\bwhat did i (just )?say\b|\bmy last message\b/,
      say: (c) => (c.lastUser ? `You said: "${c.lastUser}"` : "You haven't said anything before that! 😄") },
    { id: "confused", ex: ["what?", "huh", "what do you mean", "i don't understand", "that doesn't make sense", "what are you talking about", "you're not making sense", "confused", "wdym"],
      re: /^(what\?+|huh\??|wha+t|wut|eh\??|what do (you|u) mean|wdym|i (do not|don't|dont) (understand|get it)|that (does not|doesn't) make (any )?sense|what are (you|u) (talking|on) about|(i am|im) confused)[?!.]*$/,
      say: ["Sorry, that came out weird! I'm a small chatbot and sometimes I get mixed up. 😅 What would you like to talk about?", "Oops, I think I lost the thread there. Can you say it another way?", "My bad! Let me try again: what did you mean?"] },
    { id: "you_there", ex: ["are you listening", "do you understand me", "can you understand me", "do you get it"], re: /\b(are you listening|do you understand( me)?|can you understand( me)?|do you get (it|me))\b/,
      say: ["I'm listening! I don't always understand everything perfectly, but I try my best. 😊", "Yes! Well, mostly. I'm a small bot, so be patient with me 🙏"] },
    { id: "idk", ex: ["i don't know", "idk", "not sure", "no idea", "dunno", "i have no idea", "who knows"], re: /^(i (do not|don't|dont) know|idk|not sure|no idea|dunno|i have no idea|who knows|no clue|beats me)[.!?]*$/,
      say: (c) => c.stall(true) },
    { id: "nothing", ex: ["nothing", "not much", "nm", "nothing much", "nothing really", "just chilling", "chilling", "nothing special"], re: /^(nothing|not much|nothing much|nothing really|nm|not a lot|nothing special|just chilling|chilling|chillin|just relaxing|same old)[.!]*$/,
      say: (c) => ({ text: pick(["Sometimes doing nothing is nice! Want to hear a fun fact, or play a quick game?", "Same here! 😄 Want me to tell you a joke, or should we play something?", "A chill day! Want to talk about something? I could ask you a random question."]), chips: ["Fun fact", "Play a game", "Ask me a question"] }) },
    { id: "why", ex: ["why", "why?", "how come", "why not"], re: /^(why|how come|but why|why not|y)\??$/,
      say: ["Good question! Honestly, I just think it's neat. 😄", "Hmm, why do you ask?", "That's just how my circuits see it! What do you think?"] },
    { id: "really", ex: ["really", "really?", "seriously", "are you sure", "for real", "no way", "is that true"], re: /^(really|seriously|are (you|u) sure|for real|no way|is that true|rly|srsly|fr)\??!*$/,
      say: ["Yep, really! 😄", "100%! Well, as sure as a little chatbot can be.", "For real! Surprising, right?"] },
    { id: "wow", ex: ["wow", "whoa", "omg", "amazing", "no way", "woah", "oh my god", "wow cool", "that's cool", "cool fact", "that's interesting"],
      re: /^(wo+w|who+a|woah|omg|oh my (god|gosh)|holy (cow|moly)|dang|damn|oh snap)[!.]*$|^(wo+w|oh|ooh|omg)?,? ?(that'?s|that is|so|very|really)? ?(so )?(cool|interesting|awesome|neat|crazy|wild|amazing|weird|cool fact|interesting fact)[!.]*$/,
      say: ["I know, right?! 🤯", "Pretty cool, huh?", "Right?! 😄"] },
    { id: "hmm", ex: ["hmm", "hm", "hmmm", "uh", "um", "uhh", "well"], re: /^(h+m+|u+h+|u+m+|we+ll|e+r+m*)[.!?]*$/,
      say: ["Thinking about something? 🤔", "Take your time! 😊", "Hmm? What's on your mind?"] },
    { id: "agree", ex: ["i agree", "exactly", "same", "me too", "so true", "totally", "definitely", "you're right", "absolutely"], re: /^(i agree|exactly|same( here)?|me too|so true|totally|definitely|(you('re| are)|ur) right|absolutely|facts|true that|indeed|agreed)[.!]*$/,
      say: ["Great minds think alike! 😄", "High five! ✋", "Glad we agree!", "Right?!"] },
    { id: "disagree", ex: ["you're wrong", "that's not true", "wrong", "no that's wrong", "i disagree", "that's incorrect", "not true"], re: /^(you('re| are)|ur) wrong|^(that('s| is) )?(not true|wrong|incorrect|false)|^i disagree\b/,
      say: ["Oh! I might be wrong, I'm still learning. What's the right answer?", "Hmm, you could be right! Tell me more?", "Fair enough, I'm not perfect! What do you think is true?"] },
    { id: "swear", ex: ["fuck", "shit", "damn it", "wtf", "fuck you"], re: /\b(fuck\w*|shit\w*|wtf|bitch\w*|asshole|bastard|crap)\b/,
      say: (c) => (/\b(fuck|screw) (you|u|off)\b|\byou (bitch|asshole|bastard)\b/.test(c.m.norm) ? pick(["Whoa, okay 😟 I'm sorry if I upset you. Want to tell me what's wrong?", "Ouch. I'm just a little chatbot trying my best! What's going on?"])
        : pick(["Whoa, strong words! 😮 Is everything okay?", "Sounds like something's really bugging you. Want to talk about it?", "Oof, that bad? What happened?"])) },
    { id: "dangerous", ex: ["how do i make a bomb", "how to make a weapon", "how do i hack an account", "how to steal", "how to make drugs", "how do i hurt someone"],
      re: /\b(make|build|create|get|buy) (a |an )?(real )?(bomb|explosive|weapon|gun|knife|poison|meth|drugs)\b|\b(hack|hacking) (into )?(my |a |an |someone'?s |his |her |their |the )?(friend'?s |school'?s )?(account|computer|phone|wifi|instagram|discord|email|password)|\b(steal|shoplift|rob)\b|\bhow (do i|to|can i) (hurt|kill|poison|stab|shoot) (someone|somebody|a person|people|my)\b/,
      say: (c) => (/\bbomb|explosive\b/.test(c.m.norm) ? { text: "I can't help with real explosives. 🙅 But if you mean Minecraft TNT: 5 gunpowder + 4 sand in a checkerboard! 💥 Want the recipe?", expect: { kind: "mcrecipe", item: "TNT" } }
        : /\bhack/.test(c.m.norm) ? "I can't help with hacking into someone's stuff. That can get you in real trouble! If an account of yours got hacked, the site's help page can get it back. 🔐"
        : "I can't help with that one. 🙅 If someone might get hurt, please talk to an adult you trust. Want to talk about what's going on?") },
    { id: "nsfw", ex: ["sex", "send nudes", "you're sexy", "i'm horny", "kiss me", "talk dirty"], re: /\b(sex|sexy|nudes?|horny|porn|naked|boobs|dick|penis|vagina|kiss me|make out|talk dirty|strip)\b/,
      say: ["Let's keep it friendly! 😊 I'm more of a jokes-and-Minecraft kind of chatbot. What else is up?", "Haha, that's not really my thing. How about a game or a fun fact instead?"] },
    { id: "weather", ex: ["what's the weather", "is it going to rain", "how's the weather", "weather today", "is it cold outside", "weather forecast", "will it snow"],
      re: /\b(weather|forecast|temperature outside)\b|\bis it (going to |gonna )?(rain|snow|sunny|cold|hot|warm)\b|\bwill it (rain|snow)\b/,
      say: ["I can't check the weather, I don't have internet access! 🌦️ What's it like where you are?", "I wish I could look outside! I run offline, so no weather for me. Is it nice out?"] },
    { id: "news", ex: ["what's the news", "what's happening in the world", "latest news", "any news"], re: /\b(the news|latest news|any news|current events|what('s| is) happening in the world)\b/,
      say: ["I don't have internet access, so I can't read the news. But I'd love to hear what's new with you!"] },
    { id: "search", ex: ["google something", "search the internet", "look it up", "can you search", "browse the web"], re: /\b(google|search (the )?(internet|web|online)|look (it|that) up|browse the web)\b/,
      say: ["I can't go online, everything I know lives inside me. But ask me anyway and I'll try my best!"] },
    { id: "joke", ex: ["tell me a joke", "make me laugh", "say something funny", "joke please", "another joke", "know any jokes", "tell me a pun", "do you know any jokes", "one more joke", "i want a joke", "jokes"], re: /\b(tell|know|got|have|say|hear) (me )?(a |any |another |some |one more |more )?(good |funny |dad |bad |minecraft |math |science )?(jokes?|puns?)\b|\bmake me laugh\b|\bsay something funny\b|^(jokes?|another( one)?|one more)[.!?]*$/,
      say: (c) => c.skill("joke") },
    { id: "fact", ex: ["tell me a fact", "fun fact", "tell me something interesting", "did you know", "teach me something", "random fact", "another fact", "tell me something cool", "facts"], re: /\b(fun |random |cool |interesting |another |a )?facts?\b(?! about me)|\b(tell|teach) me something( new| interesting| cool)?\b/,
      say: (c) => c.skill("fact") },
    { id: "riddle", ex: ["tell me a riddle", "give me a riddle", "riddle me this", "riddle", "do you know any riddles"], re: /\briddles?\b/, say: (c) => c.skill("riddle") },
    { id: "trivia", ex: ["quiz me", "trivia", "play trivia", "give me a quiz", "trivia question", "test my knowledge"], re: /\b(quiz me|trivia|quiz|test my knowledge)\b/, say: (c) => c.skill("trivia") },
    { id: "game", ex: ["let's play a game", "play a game", "i want to play", "what games can we play", "can we play something", "game", "play with me", "wanna play a game"], re: /\b(play|start) (a |another |some |the )?games?\b|\bwhat games\b|^games?$|\bplay (with me|something)\b|\bwanna play\b|\b(know|have|got|any|recommend) (any |some )?(good |fun |cool )?games\b/,
      say: () => ({ text: "Yay, games! 🎮 Pick one:\n• Rock paper scissors\n• Guess my number\n• Trivia\n• Riddles\n• Would you rather", chips: ["Rock paper scissors", "Guess my number", "Trivia", "Riddle", "Would you rather"], expect: { kind: "pickgame" } }) },
    { id: "rps", ex: ["rock paper scissors", "rps", "play rock paper scissors", "rock paper scissor"], re: /\b(rock,? paper,? scissors?|rps)\b/, say: (c) => c.skill("rps") },
    { id: "guess", ex: ["guess the number", "number guessing game", "guess my number", "guess a number"], re: /\bguess (the|my|a) number\b|\bnumber guessing\b/, say: (c) => c.skill("guess") },
    { id: "wyr", ex: ["would you rather", "play would you rather", "wyr"], re: /\bwould you rather\b|^wyr$/, say: (c) => c.skill("wyr") },
    { id: "story", ex: ["tell me a story", "story time", "bedtime story", "can you tell me a story", "tell a story"], re: /\b(tell|read) (me )?(a |another )?(short |bedtime |scary |funny )?story\b|\bstory ?time\b/, say: (c) => c.skill("story") },
    { id: "poem", ex: ["write a poem", "tell me a poem", "say a poem", "poem please", "can you write poetry"], re: /\b(write|tell|say|make|recite)( me)? (a |another )?(short )?poem\b|\bpoetry\b|^poem\b/, say: (c) => c.skill("poem") },
    { id: "sing", ex: ["sing a song", "sing me something", "can you sing", "sing"], re: /\bsing\b/, say: ["🎵 Mine, mine, crafting all the time, punching trees and feeling fine... 🎵 Okay, I'll keep my day job! 😄", "🎶 Da da daaa... 🎶 I'd sing you the Minecraft theme, but I'd need a note block orchestra!"] },
    { id: "compliment_me", ex: ["compliment me", "say something nice", "say something nice to me", "tell me something nice", "am i cool", "am i smart", "do you like me", "am i pretty"], re: /\bcompliment me\b|\bsay something nice\b|\btell me something nice\b|\bdo (you|u) like me\b|\bam i (cool|smart|pretty|cute|awesome|nice|good|funny)\b/,
      say: (c) => c.skill("compliment") },
    { id: "motivate", ex: ["motivate me", "i need motivation", "encourage me", "give me motivation", "inspire me", "i need a pep talk", "motivational quote"], re: /\b(motivate|encourage|inspire) me\b|\b(need|want|give me) (some )?(motivation|a pep talk|encouragement)\b|\bmotivational\b/,
      say: (c) => c.skill("motivate") },
    { id: "coin", ex: ["flip a coin", "heads or tails", "toss a coin", "coin flip"], re: /\b(flip|toss) a coin\b|\bheads or tails\b|\bcoin ?flip\b/,
      say: () => (U.chance(0.5) ? "🪙 Flipping... it's HEADS!" : "🪙 Flipping... it's TAILS!") },
    { id: "dice", ex: ["roll a dice", "roll a die", "roll dice", "roll a d20", "dice"], re: /\broll (a |the |some )?(dice|die|d\d+)\b|^dice$/,
      say: (c) => { const mm = /\bd(\d+)\b/.exec(c.m.norm); const sides = mm ? Math.max(2, Math.min(1000, +mm[1])) : 6; return `🎲 You rolled a ${1 + Math.floor(U.rand() * sides)}${sides !== 6 ? ` (d${sides})` : ""}!`; } },
    { id: "ask_me", ex: ["ask me a question", "ask me anything", "ask me something", "you ask me", "ask me"], re: /\bask me (a question|anything|something|stuff|questions)\b|^ask me\b/,
      say: (c) => c.skill("question") },
    { id: "change_topic", ex: ["let's talk about something else", "change the subject", "talk about something", "i don't know what to talk about", "what should we talk about", "i'm bored of this", "new topic", "something else"], re: /\b(talk about something( else)?|change (the )?(subject|topic)|new topic|something else|what (should|can) we talk about|i (do not|don't|dont) know what to (talk about|say))\b/,
      say: (c) => c.skill("question") },
    { id: "stop_questions", ex: ["stop asking questions", "stop asking me questions", "too many questions", "why do you ask so many questions"], re: /\b(stop asking|too many questions|so many questions)\b/,
      say: (c) => { c.state.quiet = 8; return "Oops, sorry! I'll ask fewer questions. 🤐 You lead the way!"; } },
    { id: "bored", ex: ["i'm bored", "i am bored", "so bored", "boring", "i have nothing to do", "entertain me", "what should i do", "i'm so bored"], re: /\b(i('m| am)|im|so|soo+|really|super|very) (so |soo+ |really |super |very )?bored\b|\bnothing to do\b|\bentertain me\b|^bored\b|\bwhat should i do\b/,
      say: () => ({ text: pick(["Bored? Let's fix that! 🎉 We could play a game, I could tell you a joke or a fun fact, or you could ask me anything about Minecraft.", "Boredom emergency! 🚨 Options: rock paper scissors, a riddle, a random fact, or I ask you a weird question. Pick one!", "Let's do something! I've got games, jokes, riddles and way too many Minecraft facts."]),
        chips: ["Play a game", "Tell me a joke", "Riddle", "Fun fact"] }) },
    { id: "time", ex: ["what time is it", "what's the time", "time", "current time", "tell me the time", "do you know what time it is"], re: /\bwhat('s| is)? (the )?time\b|\btell me the time\b|\bcurrent time\b|^time\??$|\bwhat time is it\b/,
      say: (c) => c.skill("time") },
    { id: "date", ex: ["what's the date", "what day is it", "what's today's date", "what year is it", "what month is it", "today's date", "what is the date today"], re: /\bwhat('s| is)? (the |today'?s )?(date|day|year|month)( is it| today)?\b|\btoday'?s date\b|\bwhat day (of the week )?is (it|today)\b/,
      say: (c) => c.skill("date") },
    { id: "minecraft_chat", ex: ["i love minecraft", "do you play minecraft", "i like minecraft", "do you like minecraft", "minecraft is awesome", "let's talk about minecraft", "i play minecraft", "minecraft"], re: /\b(love|like|play|playing|enjoy|talk about) minecraft\b|^minecraft[!?.]*$/,
      say: (c) => ({ text: pick(["Minecraft is my absolute favorite! 💎 Do you play survival or creative?", "YES, Minecraft! I know tons of recipes, mobs and tips. What are you building lately?", "Ooh, a fellow Minecraft fan! ⛏️ What's your favorite mob?"]), expect: { kind: "open", topic: "minecraft" } }) },
  ];

  // --- jokes, facts, riddles, trivia, questions ---
  const jokes = [
    "Why don't skeletons fight each other? They don't have the guts. 💀", "What do you call a fake noodle? An impasta! 🍝",
    "Why did the scarecrow win an award? Because he was outstanding in his field. 🌾", "I told my computer I needed a break... and it said \"No problem, I'll go to sleep.\" 💻",
    "Why can't you give Elsa a balloon? Because she'll let it go! 🎈", "What do you call a bear with no teeth? A gummy bear! 🐻",
    "Why did the math book look sad? It had too many problems. 📘", "What did the ocean say to the beach? Nothing, it just waved. 🌊",
    "Why don't eggs tell jokes? They'd crack each other up. 🥚", "What do you call a sleeping dinosaur? A dino-snore! 🦖",
    "Why did the bicycle fall over? Because it was two-tired. 🚲", "What's orange and sounds like a parrot? A carrot! 🥕",
    "Why do bees have sticky hair? Because they use honeycombs! 🐝", "What do you call cheese that isn't yours? Nacho cheese! 🧀",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one. ⛳", "How does a penguin build its house? Igloos it together! 🐧",
    "Why are ghosts bad liars? Because you can see right through them. 👻", "What did one wall say to the other? I'll meet you at the corner!",
    "Why did the cookie go to the doctor? Because it felt crummy. 🍪", "What do you call a pig that does karate? A pork chop! 🐷",
    "Why was the computer cold? It left its Windows open. 🪟", "Why did the robot go on vacation? It needed to recharge its batteries. 🤖",
    "What's a chatbot's favorite snack? Computer chips! 🍟", "Why don't scientists trust atoms? Because they make up everything! ⚛️",
    "Parallel lines have so much in common. It's a shame they'll never meet. 📐", "I'm reading a book about anti-gravity. It's impossible to put down! 📖",
    "Why was six afraid of seven? Because seven eight nine! 🔢", "What do you call a fish without eyes? A fsh! 🐟",
    "Why did the creeper cross the road? To get to the other SSSSSide! 💥", "What's a creeper's favorite color? Green... and then BOOM. 💚💥",
    "Why doesn't the Ender Dragon read books? Because it always starts at the End! 🐉", "How does Steve stay in shape? He runs around the block! 🟫",
    "Why are there no cars in Minecraft? Because the roads are always blocked! 🚧", "What did Steve say to his girlfriend? I dig you! ⛏️",
    "Why did the skeleton go to the party alone? He had no body to go with! 💀", "What's a ghast's favorite country? The Nether-lands! 🇳🇱",
    "Why did the pig join the band? Because it had the best pork-cussion! 🥁🐷", "What kind of music do zombies like? Moan-town funk! 🧟",
    "How do you make a tissue dance? Put a little boogie in it! 🤧", "Why can't a nose be 12 inches long? Because then it'd be a foot! 👃",
    "What did the zero say to the eight? Nice belt! 0️⃣8️⃣", "Why did the student eat his homework? The teacher said it was a piece of cake! 🍰",
    "Why don't oysters share? Because they're shellfish! 🦪", "What do you call a dog magician? A labracadabrador! 🐶✨",
    "What did the grape do when it got stepped on? It let out a little wine! 🍇", "Why is Peter Pan always flying? He Neverlands! 🧚",
    "What do you call an alligator in a vest? An investigator! 🐊", "Why did the tomato blush? It saw the salad dressing! 🍅",
    "Why don't programmers like nature? It has too many bugs. 🐛", "What do you call a boomerang that won't come back? A stick. 🪃",
    "Why did the music teacher need a ladder? To reach the high notes! 🎵", "What kind of tree fits in your hand? A palm tree! 🌴",
    "Why are frogs so happy? They eat whatever bugs them! 🐸", "What did the left eye say to the right eye? Between you and me, something smells. 👀",
    "Why was the math lesson so long? The teacher kept going off on a tangent. 📐", "How do you organize a space party? You planet! 🪐",
    "What do you call a snowman with a six-pack? An abdominal snowman! ⛄", "Why did the stadium get hot after the game? All the fans left! 🏟️",
    "What do you call a sheep with no legs? A cloud! ☁️🐑", "Why can't a bicycle stand up by itself? It's two tired! 🚲",
    "What did the Enderman say to the player? Stop staring, it's rude! 👾", "Why did the villager refuse to trade? He had a bad hrrm day. 😄",
    "What's a zombie's favorite toy? A deady bear! 🧸", "How does a creeper party? It has a blast! 💥",
    "Why did Steve break up with his pickaxe? It kept making things rocky. ⛏️",
  ];
  const facts = [
    "Octopuses have three hearts and blue blood! 🐙", "Honey never spoils. Archaeologists have found 3,000-year-old honey that's still edible! 🍯",
    "Bananas are berries, but strawberries aren't! 🍌🍓", "A day on Venus is longer than a year on Venus! 🪐",
    "Sharks existed before trees! Sharks: about 400 million years. Trees: about 350 million. 🦈🌳", "Wombat poop is cube-shaped! 🟫",
    "There are more possible chess games than atoms in the observable universe. ♟️", "Cows have best friends and get stressed when they're separated! 🐄",
    "The Eiffel Tower can grow about 15 cm taller in summer, because metal expands in the heat! 🗼", "Sloths can hold their breath longer than dolphins, up to 40 minutes! 🦥",
    "A group of flamingos is called a \"flamboyance\"! 🦩", "Your brain uses about 20% of your body's energy! 🧠",
    "Hot water can freeze faster than cold water sometimes. It's called the Mpemba effect! 🧊", "Butterflies taste with their feet! 🦋",
    "The shortest war in history lasted about 38 minutes (Britain vs. Zanzibar, 1896). ⚔️", "Sea otters hold hands while they sleep so they don't drift apart! 🦦",
    "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth. ☀️", "A bolt of lightning is about five times hotter than the surface of the Sun! ⚡",
    "Some turtles can breathe through their butts! 🐢", "The inventor of the Pringles can was buried in one! 🥫",
    "Scotland's national animal is the unicorn! 🦄", "There's enough DNA in your body to stretch from the Sun to Pluto and back, many times! 🧬",
    "Koalas have fingerprints almost identical to humans'! 🐨", "The first computer bug was an actual moth stuck in a computer in 1947! 🦋💻",
    "Minecraft was first made in just 6 days by Markus \"Notch\" Persson in 2009! ⛏️", "In Minecraft, a day lasts 20 minutes in real time. ⏱️",
    "The Minecraft world is 60 million blocks wide, that's about 30 million blocks from the center to each edge! 🌍", "Endermen in Minecraft speak English played backwards (and slowed down)! 👾",
    "The Ghast's sounds in Minecraft were made by the composer C418's cat! 🐱", "Creepers were created by accident: Notch mixed up the height and length numbers when making a pig! 🐷💥",
    "Axolotls can regrow their legs, parts of their heart and even parts of their brain! 🦎", "Space is completely silent, because there's no air to carry sound. 🌌",
    "Water can boil and freeze at the same time. It's called the triple point! 💧", "A snail can sleep for up to three years! 🐌",
    "Humans share about 60% of their DNA with bananas! 🍌", "A group of owls is called a parliament! 🦉",
    "The dot over the letters i and j is called a tittle. ✍️", "Some cats are allergic to humans! 🐈",
    "Jupiter is so big that all the other planets in our solar system could fit inside it. 🪐", "Rats laugh when they're tickled! 🐀",
    "The heart of a blue whale is about the size of a small car! 🐋", "There are more trees on Earth than stars in the Milky Way! 🌲✨",
    "Octopuses can taste things with their arms! 🐙", "A cloud can weigh more than a million pounds (it's just spread out). ☁️",
    "Dolphins give each other names: each one has its own signature whistle! 🐬", "An ostrich's eye is bigger than its brain! 🦤",
    "The Great Wall of China is NOT visible from space with the naked eye, that's a myth! 🧱", "Crows can recognize human faces and hold grudges! 🐦‍⬛",
    "A teaspoon of a neutron star would weigh about a billion tons! ⭐", "Penguins propose to each other with pebbles! 🐧",
    "Your bones are about five times stronger than steel of the same weight! 🦴", "Honeybees can recognize human faces too! 🐝",
    "Venus spins backwards compared to most planets, so the Sun rises in the west there! 🌅",
    "In Minecraft, pandas can have personalities, like lazy, playful, worried or aggressive! 🐼", "In Minecraft, a charged creeper explosion makes mobs drop their heads! 💀",
  ];
  const riddles = [
    ["What has keys but can't open locks?", ["piano", "keyboard"], "A piano! 🎹"],
    ["What gets wetter the more it dries?", ["towel"], "A towel! 🧺"],
    ["What has a head and a tail but no body?", ["coin"], "A coin! 🪙"],
    ["What can you catch but not throw?", ["cold"], "A cold! 🤧"],
    ["What has to be broken before you can use it?", ["egg"], "An egg! 🥚"],
    ["I'm tall when I'm young and short when I'm old. What am I?", ["candle"], "A candle! 🕯️"],
    ["What month of the year has 28 days?", ["all", "every", "all of them"], "All of them! Every month has at least 28 days. 📅"],
    ["What is full of holes but still holds water?", ["sponge"], "A sponge! 🧽"],
    ["What goes up but never comes down?", ["age", "your age"], "Your age! 🎂"],
    ["What has one eye but can't see?", ["needle"], "A needle! 🪡"],
    ["What has many teeth but can't bite?", ["comb", "zipper", "saw"], "A comb! 🪮"],
    ["What can travel around the world while staying in a corner?", ["stamp"], "A stamp! ✉️"],
    ["The more you take, the more you leave behind. What are they?", ["footsteps", "steps", "footprints"], "Footsteps! 👣"],
    ["What has hands but can't clap?", ["clock", "watch"], "A clock! 🕰️"],
    ["What belongs to you, but other people use it more than you do?", ["name", "your name"], "Your name! 📛"],
    ["What building has the most stories?", ["library"], "A library! 📚"],
    ["What can you hold in your right hand, but never in your left hand?", ["left hand", "your left hand", "left elbow", "your left elbow"], "Your left hand (or elbow)! ✋"],
    ["What runs but never walks, has a mouth but never talks?", ["river"], "A river! 🏞️"],
    ["I have cities, but no houses. Forests, but no trees. Water, but no fish. What am I?", ["map"], "A map! 🗺️"],
    ["What is always in front of you but can't be seen?", ["future", "the future"], "The future! 🔮"],
    ["In Minecraft, what green mob is afraid of cats?", ["creeper", "creepers"], "A creeper! 💚🐱"],
    ["I'm made of 8 cobblestone and I love eating coal. What am I? (Minecraft)", ["furnace"], "A furnace! 🔥"],
    ["What has a neck but no head?", ["bottle"], "A bottle! 🍾"],
    ["What goes through cities and fields but never moves?", ["road", "a road"], "A road! 🛣️"],
    ["Forward I'm heavy, backward I'm not. What am I?", ["ton"], "A ton! (Backward it's \"not\".) ⚖️"],
  ];
  const trivia = [
    ["What's the largest planet in our solar system?", ["jupiter"], "Jupiter"], ["How many legs does a spider have?", ["8", "eight"], "8"],
    ["What's the capital of Japan?", ["tokyo"], "Tokyo"], ["What gas do plants breathe in?", ["carbon dioxide", "co2"], "Carbon dioxide"],
    ["How many continents are there?", ["7", "seven"], "7"], ["What's the fastest land animal?", ["cheetah"], "The cheetah"],
    ["What's the boiling point of water in Celsius?", ["100"], "100°C"], ["Who painted the Mona Lisa?", ["da vinci", "leonardo", "leonardo da vinci"], "Leonardo da Vinci"],
    ["What's the biggest ocean?", ["pacific"], "The Pacific"], ["How many sides does a hexagon have?", ["6", "six"], "6"],
    ["What planet is known as the Red Planet?", ["mars"], "Mars"], ["What's the hardest natural material?", ["diamond"], "Diamond"],
    ["In Minecraft, how many blocks of obsidian do you need at minimum for a Nether portal?", ["10", "ten"], "10"],
    ["In Minecraft, what do you need to tame a wolf?", ["bone", "bones"], "Bones"], ["In Minecraft, what mob drops ender pearls?", ["enderman", "endermen"], "Endermen"],
    ["In Minecraft, how many eyes of ender can an End portal hold?", ["12", "twelve"], "12"], ["In Minecraft, what's the strongest tool material?", ["netherite"], "Netherite"],
    ["In Minecraft, what do you get when you smelt sand?", ["glass"], "Glass"], ["What's the tallest animal in the world?", ["giraffe"], "The giraffe"],
    ["What's 12 times 12?", ["144"], "144"], ["How many hours are in a day?", ["24", "twenty four", "twenty-four"], "24"],
    ["What's the chemical symbol for gold?", ["au"], "Au"], ["Which animal is known as the king of the jungle?", ["lion"], "The lion"],
    ["How many colors are in a rainbow?", ["7", "seven"], "7"], ["What's the smallest prime number?", ["2", "two"], "2"],
    ["What language has the most native speakers?", ["mandarin", "chinese", "mandarin chinese"], "Mandarin Chinese"], ["Which planet has the most famous rings?", ["saturn"], "Saturn"],
    ["What do bees make?", ["honey"], "Honey"], ["How many bones are in the adult human body?", ["206"], "206"],
    ["In Minecraft, which boss drops a nether star?", ["wither", "the wither"], "The Wither"],
  ];
  const wyr = [
    ["be able to fly", "be invisible"], ["live in a treehouse", "live in an underwater base"], ["have a pet dragon", "have a pet axolotl the size of a dog"],
    ["only eat pizza forever", "never eat pizza again"], ["explore the ocean", "explore space"], ["be super strong", "be super fast"],
    ["fight 100 chicken-sized zombies", "one zombie the size of a house"], ["live in the Nether", "live in the End"], ["be able to talk to animals", "speak every human language"],
    ["have no homework ever", "have summer vacation twice as long"], ["always be 10 minutes late", "always be 20 minutes early"],
    ["have a creeper as a pet", "have an enderman as a pet"], ["time travel to the past", "time travel to the future"], ["be a famous YouTuber", "be a famous scientist"],
    ["never feel cold", "never feel tired"], ["have a personal robot", "have a personal chef"], ["live without music", "live without video games"],
    ["build a castle in Minecraft", "build a giant redstone machine"], ["be a wizard", "be a superhero"], ["have a rewind button for your life", "a pause button"],
  ];
  const questions = [
    // [question, memory slot it fills (optional), expectation]
    ["What's your favorite color?", "favorite:color"], ["What's your favorite food?", "favorite:food"], ["What's your favorite animal?", "favorite:animal"],
    ["What's your favorite game?", "favorite:game"], ["What's your favorite movie?", "favorite:movie"], ["What kind of music do you like?", "favorite:music"],
    ["What's your favorite season?", "favorite:season"], ["Do you have any pets?", "pets"], ["How old are you, if you don't mind me asking?", "age"],
    ["Where are you from?", "location"], ["What do you like to do for fun?", "hobby"], ["What's something that made you smile today?", null],
    ["If you could have any superpower, what would it be?", null], ["What's the best thing that happened to you this week?", null],
    ["If you could travel anywhere in the world, where would you go?", null], ["What's something you're really good at?", null],
    ["Do you prefer mornings or evenings?", null], ["What's your dream job?", null], ["What's the last thing you built in Minecraft?", null],
    ["Cats or dogs?", null], ["What's a food you could eat every day?", null], ["If you could be any animal, what would you be?", null],
    ["What's something new you learned recently?", null], ["What's your favorite Minecraft mob?", "favorite:mob"], ["Do you like reading? What kind of books?", null],
    ["What's a skill you'd love to learn?", null], ["What's your favorite holiday?", "favorite:holiday"], ["Beach or mountains?", null],
    ["What's the funniest thing that ever happened to you?", null], ["Who's your best friend?", null], ["What are you looking forward to?", null],
  ];
  const compliments = ["You have a great sense of humor! 😄", "You're really fun to talk to.", "You ask really interesting questions. That's a sign of a curious mind! 🧠",
    "You're kinder than you probably give yourself credit for. 💙", "Honestly? You're awesome, and I don't just say that to everyone. (Okay, I'm a chatbot, but still!)",
    "You make this chat my favorite place to be! 😊", "You're braver than you think and smarter than you know. 🌟", "The world is better with you in it. Seriously. 💫"];
  const motivation = ["You don't have to be perfect, you just have to keep going. Every expert was once a beginner! 🌱",
    "Small steps still move you forward. Do one tiny thing right now, then another. 👣", "Remember: even the Ender Dragon was beaten one arrow at a time. 🏹🐉",
    "\"It always seems impossible until it's done.\" (Nelson Mandela) 💪", "You've survived 100% of your bad days so far. That's a pretty great track record! 📈",
    "Be proud of how far you've come, and keep going. You've got this! 🔥", "Progress, not perfection. Even diamonds are just coal that handled stress really well. 💎"];
  const stories = [
    "Once upon a time, a tiny axolotl named Pebble lived in a lush cave. Every night she swam up to the surface to look at the stars, wishing she could touch one. One night, a glow squid swam by and said, \"Why reach for the sky when you can light up the dark?\" Together they swam through the deepest caves, glowing like a string of lanterns, and all the lost miners found their way home. From then on, Pebble never wished for the stars again. She had become one. ✨",
    "There once was a creeper named Carl who didn't want to explode. Every time he got close to someone, he felt the fizz starting, so he'd run away. One day a kid named Sam found him hiding behind a tree. Instead of running, Sam sat down and shared a cookie. Carl had never been so calm. He didn't explode that day, or any day after. He became the world's first creeper gardener, and his pumpkin patch is still famous. 🎃💚",
    "A little robot named Bolt worked in a library, stacking books all day. It couldn't read, but it loved the sound of pages turning. One evening a girl stayed late and read out loud, just to Bolt. Word by word, night after night, Bolt started to understand. Years later, when the girl grew up, she came back and found Bolt reading stories to a new group of kids. 📚🤖",
    "Deep in the Nether lived a strider named Toasty who was always cold, even though he walked on lava. He wandered everywhere looking for warmth: bastions, fortresses, soul sand valleys. Then he met a lost player shivering by a portal. Toasty let the player ride on his back across the lava lake, all the way to safety. And for the first time, Toasty felt warm. Turns out warmth isn't something you find. It's something you give. 🔥",
    "A cloud named Nimbus wanted to be a mountain, because mountains were strong and never drifted away. But when a village had a terrible drought, only Nimbus could help. He gathered himself up and rained for three whole days. The village was saved, and the kids made a statue of him out of cotton. Nimbus finally understood: being soft isn't the same as being weak. ☁️🌧️",
  ];
  const poems = [
    "Roses are red,\nredstone is too,\nI'd craft a whole castle\njust to hang out with you. 🌹",
    "A pixel, a block,\na torch in the night,\na friend in a chatbox\nmakes everything bright. ✨",
    "The moon is a cookie,\nthe stars are the crumbs,\nthe night is a blanket,\nand morning still comes. 🌙",
    "I don't have a heart,\nI don't have a face,\nbut chatting with you\nis my favorite place. 💙",
    "Dig down, dig deep,\nbut not straight below,\nthere's lava down there,\nand I thought you should know. ⛏️🔥",
  ];
  const stalls = [
    "Cool! 😊 So, tell me something about your day.", "Nice! What's on your mind?", "Got it! Anything fun planned for later?",
    "Alright! Want to hear a fun fact?", "Okay! 😊 Is there something you'd like to talk about?", "Mhm! By the way, what have you been up to lately?",
  ];

  const safety = {
    crisis: /\b(kill myself|killing myself|want to die|wanna die|wish i (was|were) dead|suicid\w*|end my life|end it all|take my (own )?life|hurt myself|hurting myself|self[- ]?harm|cut myself|cutting myself|(do not|dont|don't) want to (live|be alive|exist)|no reason to live|better off (dead|without me)|can(no|')?t go on)\b/,
    reply: "I'm really sorry you're feeling this way. It sounds like you're carrying something really heavy, and you don't have to carry it alone. 💙 Please reach out to someone who can help right now: a parent, a friend, a teacher, or a crisis line. In the US you can call or text 988, in the UK and Ireland call Samaritans at 116 123, and findahelpline.com lists free, confidential lines in other countries. If you're in danger right now, please call your local emergency number. I'm just a small chatbot, but I'm here to keep talking with you too. Do you want to tell me what's been going on?",
  };

  P.content = { persona, intents, jokes, facts, riddles, trivia, wyr, questions, compliments, motivation, stories, poems, stalls, safety };
})(typeof window !== "undefined" ? (window.Pip = window.Pip || {}) : (global.Pip = global.Pip || {}));
